=== wz18567908/wangzheng/source/ctcloud-dlc/src/main/conf/dataloaders/dataloader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="DataLoader">
        <xs:annotation>
            <xs:documentation>
                The DataLoader root
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Description" type="xs:string" minOccurs="0"/>
                <xs:element name="Reader">
                    <xs:annotation>
                        <xs:documentation>
                            The plug-in Reader
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Properties" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Property" minOccurs="1" maxOccurs="unbounded">
                                            <xs:annotation>
                                                <xs:documentation>
                                                    The properties include: executable: The execute shell script; skipHeader: Need to skip the header or not; timeout: Period in seconds before the loader kill the process; delimiter: Delimiter of the CSV file, ',' by default; quote: Quote character in the CSV file, '"' by default; escape: Escape character in the CSV file, '\' by default.
                                                </xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Extra" minOccurs="0" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>
                                        Header of a table. Note: The first column is always TABLE_NAME. This is mandatory for the PipeReader. The name of the table is case sensitive. The table name in the output must matches the table name. Specified here and the table name specified in the SQL element.
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Headers" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Header" minOccurs="1" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="table" type="xs:string" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="class" type="xs:string" use="required">
                            <xs:annotation>
                                <xs:documentation>
                                    Defined which Reader implement will be used to get data. The Class attribute refer the Class name or Reader implements. This Class can be developed by customer.
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="maxBufferSize" use="optional">
                            <xs:annotation>
                                <xs:documentation>
                                    Defined which Writer will be used to load the output of Reader into DataBase. maxBatchSize: Defined how many records will be committed into DataBase one time. errorHandler: What the next behavior when error occurs during data write. * dlp - persist data to local disk, mainly used for sampling loader * exit - exit the data loader with error, mainly used for file loader.
                                </xs:documentation>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="10000"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Writer">
                    <xs:annotation>
                        <xs:documentation>
                            The common writer modle
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SQL" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Statement">
                                            <xs:annotation>
                                                <xs:documentation>
                                                    The insert sql statement. The SQL statement will be defined in this element. If The Field sub elements map the output of Reader to DataBase table. The Name attribute is the key of Reader output. The Column attribute is the column name of DataBase Table.
                                                </xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="Parameters" minOccurs="0" maxOccurs="unbounded">
                                            <xs:annotation>
                                                <xs:documentation>
                                                    The following types can be taken (case-insensitive). String - string/text value. If no type explicitly specified, this will be a default type. Numeric - numeric value, the same as double value. Double - double value. Integer - integer/long value. Timestamp - timestamp value, the format of the string is either 'yyyy-MM-dd HH:mm:ss' or 'yyyy-mm-dd HH:mm:ss.SSS'. Date - date value, the format of the string is 'yyyy-MM-dd'. Time - time value, the format of the string 'HH:mm:ss'.
                                                </xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Param" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="value" type="xs:string" use="required"/>
                                                            <xs:attribute name="type" type="xs:string"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="ds">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="CloudDB"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="table" type="xs:string" use="required"/>
                                    <xs:attribute name="maxBatchSize" use="optional">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1"/>
                                                <xs:maxInclusive value="10000"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="maxBatchSize" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="10000"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="errorHandler" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== wz18567908/wangzheng/source/ctcloud-dlc/src/main/conf/dataloaders/lsf_loader.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataLoader xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataloader.xsd">

    <Description><![CDATA[Load data from lsf accounting files.]]></Description>
    <Reader class="com.clustertech.cloud.dlc.framework.reader.lsf.LSFJobReader" maxBufferSize="30">
        <Properties>
            <Property name="timeout">600</Property>
            <Property name="delimiter"><![CDATA[ ]]></Property>
            <Property name="quote"><![CDATA["]]></Property>
            <Property name="escape"><![CDATA[$]]></Property>
        </Properties>
        <Extra>
            <Headers>
                <Header table="LSF_LIVE_JOB">TABLE_NAME,JOB_ID,JOB_ARRAY_INDEX,JOB_NAME,USER_NAME,QUEUE,SUBMIT_TIME,START_TIME,END_TIME,EXEC_HOSTSTR,FROM_HOST,COMMAND,PROJECT_NAME,WORKLOAD_TYPE,JOB_STATUS,EXIT_STATUS,CLUSTER_NAME</Header>
            </Headers>
        </Extra>
    </Reader>
    <Writer maxBatchSize="30" errorHandler="EXIT">
        <SQL ds="CloudDB" table="LSF_LIVE_JOB" maxBatchSize="5000">
            <Statement>
                <![CDATA[
                  REPLACE INTO LSF_LIVE_JOB(
                    JOB_ID,
                    JOB_ARRAY_INDEX,
                    JOB_NAME,
                    USER_NAME,
                    QUEUE,
                    SUBMIT_TIME,
                    START_TIME,
                    END_TIME,
                    EXEC_HOSTSTR,
                    FROM_HOST,
                    COMMAND,
                    PROJECT_NAME,
                    WORKLOAD_TYPE,
                    JOB_STATUS,
                    EXIT_STATUS,
                    CLUSTER_NAME
                  )VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ]]>
            </Statement>
            <Parameters>
                <Param value="JOB_ID"/>
                <Param value="JOB_ARRAY_INDEX"/>
                <Param value="JOB_NAME"/>
                <Param value="USER_NAME"/>
                <Param value="QUEUE"/>
                <Param value="SUBMIT_TIME"/>
                <Param value="START_TIME"/>
                <Param value="END_TIME"/>
                <Param value="EXEC_HOSTSTR"/>
                <Param value="FROM_HOST"/>
                <Param value="COMMAND"/>
                <Param value="PROJECT_NAME"/>
                <Param value="WORKLOAD_TYPE"/>
                <Param value="JOB_STATUS"/>
                <Param value="EXIT_STATUS"/>
                <Param value="CLUSTER_NAME"/>
            </Parameters>
        </SQL>
    </Writer>
</DataLoader>
